### ISSUE TITLE
Running with mobx decorator got error

### ISSUE THREAD

**Issue by fangwei18** [trivago/prettier-plugin-sort-imports#109]
Error messages are as follows:

```sh
SyntaxError: This experimental syntax requires enabling one of the following parser plugin(s): 'decorators-legacy, decorators' (20:0)

...

 at Object._raise (.../node_modules/@trivago/prettier-plugin-sort-imports/node_modules/@babel/parser/lib/index.js:816:17)
    at Object.raiseWithData (.../node_modules/@trivago/prettier-plugin-sort-imports/node_modules/@babel/parser/lib/index.js:809:17)
    at Object.expectOnePlugin (.../node_modules/@trivago/prettier-plugin-sort-imports/node_modules/@babel/parser/lib/index.js:9920:18)
    at Object.parseDecorator (.../node_modules/@trivago/prettier-plugin-sort-imports/node_modules/@babel/parser/lib/index.js:12727:10)
    at Object.parseDecorators (.../node_modules/@trivago/prettier-plugin-sort-imports/node_modules/@babel/parser/lib/index.js:12709:30)
    at Object.parseStatement (.../node_modules/@trivago/prettier-plugin-sort-imports/node_modules/@babel/parser/lib/index.js:12542:12)
    at Object.parseBlockOrModuleBlockBody (.../node_modules/@trivago/prettier-plugin-sort-imports/node_modules/@babel/parser/lib/index.js:13134:25)
    at Object.parseBlockBody (.../node_modules/@trivago/prettier-plugin-sort-imports/node_modules/@babel/parser/lib/index.js:13125:10)
    at Object.parseProgram (.../node_modules/@trivago/prettier-plugin-sort-imports/node_modules/@babel/parser/lib/index.js:12468:10)
```

**Comment by juanrgm** [comment]
The problem was introduced [here](https://github.com/trivago/prettier-plugin-sort-imports/commit/486cfa0e56f985f3c78d9c29b2a59c5c14b6e003#diff-7ad74220ec04a272ca8eb23d31dd2af58f18076c0d8624630e40e57533b585cdR21) (v3.0.0).

Why `decorators-legacy` and `class-properties` plugins were deleted?

**Comment by blutorange** [comment]
Hmm, if you read through #88 it seems this was an intentional change, these plugins are not activated by default. You can use the option

>   "importOrderParserPlugins" : ["classProperties", "decorators-legacy"]

I guess it should be mentioned in the migration guide though.

**Comment by juanrgm** [comment]
But why were they deleted from plugin default list? 

Now I must create a `.prettierrc` file (with `importOrderParserPlugins` option) in every project where I use decorators.

**Comment by blutorange** [comment]
You might need for the authors to reply, but from what I can tell, it's because those are either deprecated features or experimental ES proposals. At least decorators as implemented by TypeScript are based on an outdated proposal.  So I guess it makes sense not to include them by default. It's a breaking change though, which is why the version was bumped to 3.x

> Now that we are adding this, we need to remove the legacy decorator that we are adding automatically

**Comment by juanrgm** [comment]
The solution to support both decorator plugins it was to support none by default, but with the new option added (`importOrderParserPlugins`) you can override that default config, no?

Now, `prettier`, without `prettier-plugin-sort-imports`, can successfully format the next code:
```typescript
function test(constructor: Function) {}
@test
class A {}
```

But if you install `prettier-plugin-sort-imports`:

```
[error] src\index.ts: SyntaxError: This experimental syntax requires enabling one of the following parser plugin(s): 'decorators-legacy, decorators' (5:0)
```

Adding the plugins to `importOrderParserPlugins` fixes the issue, but was it mandatory requirement delete the default plugins?

**Comment by byara** [comment]
Hey @fangwei18 and @juanrgm, sorry that you are facing this issue. As you know, we were adding few babel parser plugins by default in version 2, `legacy-decorator`, `typescript` and `jsx`. The issue is there are other proposals for decorators and passing 2 parser plugins to babel for the decorators is not possible. Therefore we decided to let the user decides what parser to pass.
