### ISSUE TITLE
TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by jlarmstrongiv** [trivago/prettier-plugin-sort-imports#140]
**Your Environment**
 * **Prettier version**: 2.5.1
 * **node version** [12.x.x, 14.x.x]: v14.18.1
 * **package manager**: [npm@7, pnpm@6, yarn@2] 8.1.0
 * **IDE**: [VScode, Webstorm, CLI] VSCode

**Describe the bug**

Prettier throws errors in the logs and does not format my code.

**To Reproduce**

N/A

**Expected behavior**

Prettier formats my code without error!

**Screenshots, code sample, etc**

**Configuration File (cat .prettierrc, prettier.config.js, .prettier.js)**

prettier.config.mjs
```js
const tailwind = require("prettier-plugin-tailwindcss");
const sortImports = require("@trivago/prettier-plugin-sort-imports");

module.exports = {
  // prettier options https://prettier.io/docs/en/options.html
  semi: true,
  jsxSingleQuote: false,
  trailingComma: "all",
  bracketSpacing: true,
  bracketSameLine: false,
  arrowParens: "always",
  endOfLine: "lf",

  // import sorter options https://www.npmjs.com/package/@trivago/prettier-plugin-sort-imports
  importOrder: [
    "<THIRD_PARTY_MODULES>",
    "^@configs/(.*)$",
    "^@clis/(.*)$",
    "^@nodejs/(.*)$",
    "^@reactjs/(.*)$",
    "^@universaljs/(.*)$",
    "^[./]",
  ],
  importOrderSeparation: false,
  importOrderSortSpecifiers: true,
  importOrderGroupNamespaceSpecifiers: true,

  // plugin incompatibilities https://github.com/tailwindlabs/prettier-plugin-tailwindcss/issues/9#issuecomment-1021028722
  plugins: [
    {
      parsers: {
        typescript: {
          ...tailwind.parsers.typescript,
          preprocess: sortImports.parsers.typescript.preprocess,
        },
      },
    },
  ],
};
```

**Error log**

```
["ERROR" - 8:15:17 PM] Error formatting document.
TypeError: Cannot read property 'map' of undefined
	at Object.getExperimentalParserPlugins (/Users/jlarmst/Desktop/monorepos/turbo-monorepo/configs/prettier/node_modules/@trivago/prettier-plugin-sort-imports/lib/src/utils/get-experimental-parser-plugins.js:10:37)
	at Object.preprocessor [as preprocess] (/Users/jlarmst/Desktop/monorepos/turbo-monorepo/configs/prettier/node_modules/@trivago/prettier-plugin-sort-imports/lib/src/preprocessor.js:18:52)
	at Object.parse$d [as parse] (/Users/jlarmst/Desktop/monorepos/turbo-monorepo/node_modules/prettier/index.js:12970:21)
	at coreFormat (/Users/jlarmst/Desktop/monorepos/turbo-monorepo/node_modules/prettier/index.js:14525:16)
	at formatWithCursor$1 (/Users/jlarmst/Desktop/monorepos/turbo-monorepo/node_modules/prettier/index.js:14765:14)
	at /Users/jlarmst/Desktop/monorepos/turbo-monorepo/node_modules/prettier/index.js:60959:12
	at Object.format (/Users/jlarmst/Desktop/monorepos/turbo-monorepo/node_modules/prettier/index.js:60979:12)
	at t.default.format (/Users/jlarmst/.vscode-insiders/extensions/esbenp.prettier-vscode-9.3.0/dist/extension.js:1:13219)
	at async t.PrettierEditProvider.provideEdits (/Users/jlarmst/.vscode-insiders/extensions/esbenp.prettier-vscode-9.3.0/dist/extension.js:1:10196)
	at async y.provideDocumentFormattingEdits (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:98503)
```

**Contribute to @trivago/prettier-plugin-sort-imports**

- [ ] I'm willing to fix this bug 🥇

**Comment by giacomoferretti** [comment]
Did you fix this?
