### ISSUE TITLE
Migrate to Prettier v3

### ISSUE THREAD

**Issue by sosukesuzuki** [trivago/prettier-plugin-sort-imports#177]
**Is your feature request related to a problem?**
N/A

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
N/A

**Additional context**

Sorry, I ignore the issue template..

---

Hi, I am a maintainer at Prettier.

The Prettier team is currently working on v3(still alpha).
v3 will include breaking changes to the plugin interface.
Please see https://github.com/prettier/prettier/releases/tag/3.0.0-alpha.2 for more information.

I created this issue to help major plugins migrate to Prettier v3.

Myself and @fisker have created a migration guide which you can see here:

https://github.com/prettier/prettier/wiki/How-to-migrate-my-plugin-to-support-Prettier-v3%3F

If you have any questions, feel free to mention us. We can help you.

If you have already migrated to Prettier v3, sorry but please close this issue.

**Comment by IanVS** [comment]
Hi @sosukesuzuki, thanks for the issue.  There's an existing one, https://github.com/trivago/prettier-plugin-sort-imports/issues/171, mentioning that this plugin does not work with V3.  I maintain a fork of this plugin, and also have the issue, so I dug in a little, and identified https://github.com/prettier/prettier/issues/13729 as the root cause.  Maybe you can take a look and let us all know how we should proceed?

**Comment by NiklasPor** [comment]
Hey all, you could try telling your users to explicitly specify the plugin:
```json
// .prettierrc
{
  "plugins": ["prettier-plugin-sort-imports"],
}
```

I'm having the same issue with [prettier-plugin-organize-attributes](https://www.npmjs.com/package/prettier-plugin-organize-attributes) and that's my workaround for now 👀 If you find any better solutions I'd love it if you would note them down here or in the other thread 👍

**Comment by IronTony** [comment]
Same here:
.prettierrc

```
module.exports = {
  printWidth: 120,
  tabWidth: 2,
  trailingComma: 'all',
  singleQuote: true,
  semi: true,
  plugins: ['@trivago/prettier-plugin-sort-imports'],
  importOrder: ['^@core/(.*)$', '^@server/(.*)$', '^@ui/(.*)$', '^[./]'],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
};

```

**Comment by sidneifjr** [comment]
I have the same setup as IronTony, but my VSCode output window returns the following:

`["ERROR"` - 2:07:35 PM] Error resolve node module 'prettier-plugin-sort-imports'
Error: Error resolve node module 'prettier-plugin-sort-imports'
    at n (c:\Users\SIDNEI\.vscode\extensions\esbenp.prettier-vscode-10.1.0\dist\extension.js:1:2718)
    at c:\Users\SIDNEI\.vscode\extensions\esbenp.prettier-vscode-10.1.0\dist\extension.js:1:3068
    at Array.map (<anonymous>)
    at t.resolveConfigPlugins (c:\Users\SIDNEI\.vscode\extensions\esbenp.prettier-vscode-10.1.0\dist\extension.js:1:3003)
    at t.ModuleResolver.resolveConfig (c:\Users\SIDNEI\.vscode\extensions\esbenp.prettier-vscode-10.1.0\dist\extension.js:1:7290)
    at t.default.getSelectors (c:\Users\SIDNEI\.vscode\extensions\esbenp.prettier-vscode-10.1.0\dist\extension.js:1:11562)
    at t.default.handleActiveTextEditorChanged (c:\Users\SIDNEI\.vscode\extensions\esbenp.prettier-vscode-10.1.0\dist\extension.js:1:10924)`
