### ISSUE TITLE
Formatting fails with error "'export declare' must be followed by an ambient declaration" in d.ts file

### ISSUE THREAD

**Issue by xMort** [trivago/prettier-plugin-sort-imports#203]
**Your Environment**
 * **Prettier version**: 2.0.4
 * **node version**: 16.13.0
 * **package manager**:  yarn@1.22.17
 * **IDE**: CLI

**Describe the bug**

When I run prettier with sort import plugin, it failed on my `typings/globals.d.ts` file with the following error:
`typings/globals.d.ts: SyntaxError: 'export declare' must be followed by an ambient declaration. (1:15)`

There was no problem with the file before the sort imports plugin was installed.

**To Reproduce**

Run prettier via `prettier --write './typings/globals.d.ts'` on the file in samples section

**Expected behavior**

File is formatted and no error is thrown.

**Screenshots, code sample, etc**

````
export declare global {
    export const DEBUG_LAYOUTS: boolean;
    export const COMMIT_HASH: string | undefined;
    export function __webpack_init_sharing__(scope: string): Promise<void>;
    export let __webpack_share_scopes__: any;

    declare module "*.png" {
        const value: any;
        export default value;
    }

    declare module "*.ico" {
        const value: any;
        export default value;
    }

    declare module "*.svg" {
        const value: any;
        export default value;
    }
}
````

**Configuration File (.prettierrc**

````
{
  "printWidth": 110,
  "tabWidth": 4,
  "trailingComma": "all",
  "importOrder": ["^\\.\\./?", "^\\./?"],
  "importOrderSeparation": true,
  "importOrderSortSpecifiers": true
}
````

**Error log**

````
yarn run v1.22.17
$ prettier --write './typings/globals.d.ts'
typings/globals.d.ts
[error] typings/globals.d.ts: SyntaxError: 'export declare' must be followed by an ambient declaration. (1:15)
[error]    1 | export declare global {
[error]    2 |     export const DEBUG_LAYOUTS: boolean;
[error]    3 |     export const COMMIT_HASH: string | undefined;
[error]    4 |     export function __webpack_init_sharing__(scope: string): Promise<void>;
[error]    5 |     export let __webpack_share_scopes__: any;
[error]    6 |
[error]    7 |     declare module "*.png" {
[error]    8 |         const value: any;
[error]    9 |         export default value;
[error]   10 |     }
[error]   11 |
[error]   12 |     declare module "*.ico" {
[error]   13 |         const value: any;
[error]   14 |         export default value;
[error]   15 |     }
[error]   16 |
[error]   17 |     declare module "*.svg" {
[error]   18 |         const value: any;
[error]   19 |         export default value;
[error]   20 |     }
[error]   21 | }
[error]   22 |
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
````

**Contribute to @trivago/prettier-plugin-sort-imports**

- [ ] I'm willing to fix this bug 🥇

**Comment by OliverJAsh** [comment]
I'm facing a similar issue with a `.d.ts` file, although in my case the error message is different:

```
SyntaxError: Missing initializer in const declaration
```

`foo.d.ts`:
```ts
export const colorWhite: string;
```


<img width="1840" alt="image" src="https://user-images.githubusercontent.com/921609/222885939-a506b640-4d0f-4a7c-a2ec-9664d555b1c2.png">

```
["ERROR" - 08:38:26] Error formatting document.
["ERROR" - 08:38:26] Missing initializer in const declaration. (1:31)
  1 | export const colorWhite: string;
SyntaxError: Missing initializer in const declaration. (1:31)
  1 | export const colorWhite: string;
    at instantiate (/Users/oliverash/Development/temp/prettier-test/node_modules/@babel/parser/src/parse-error/credentials.ts:62:21)
    at toParseError (/Users/oliverash/Development/temp/prettier-test/node_modules/@babel/parser/src/parse-error.ts:60:12)
    at TypeScriptParserMixin.raise (/Users/oliverash/Development/temp/prettier-test/node_modules/@babel/parser/src/tokenizer/index.ts:1464:19)
    at TypeScriptParserMixin.parseVar (/Users/oliverash/Development/temp/prettier-test/node_modules/@babel/parser/src/parser/statement.ts:1525:16)
    at TypeScriptParserMixin.parseVarStatement (/Users/oliverash/Development/temp/prettier-test/node_modules/@babel/parser/src/parser/statement.ts:1169:10)
    at TypeScriptParserMixin.parseVarStatement (/Users/oliverash/Development/temp/prettier-test/node_modules/@babel/parser/src/plugins/typescript/index.ts:2806:33)
    at TypeScriptParserMixin.parseStatementContent (/Users/oliverash/Development/temp/prettier-test/node_modules/@babel/parser/src/parser/statement.ts:537:21)
    at TypeScriptParserMixin.parseStatementContent (/Users/oliverash/Development/temp/prettier-test/node_modules/@babel/parser/src/plugins/typescript/index.ts:2857:20)
    at TypeScriptParserMixin.parseStatementLike (/Users/oliverash/Development/temp/prettier-test/node_modules/@babel/parser/src/parser/statement.ts:416:17)
    at TypeScriptParserMixin.parseStatementListItem (/Users/oliverash/Development/temp/prettier-test/node_modules/@babel/parser/src/parser/statement.ts:365:17)
    at TypeScriptParserMixin.parseExportDeclaration (/Users/oliverash/Development/temp/prettier-test/node_modules/@babel/parser/src/parser/statement.ts:2542:17)
    at TypeScriptParserMixin.parseExportDeclaration (/Users/oliverash/Development/temp/prettier-test/node_modules/@babel/parser/src/plugins/typescript/index.ts:3109:15)
    at TypeScriptParserMixin.maybeParseExportDeclaration (/Users/oliverash/Development/temp/prettier-test/node_modules/@babel/parser/src/parser/statement.ts:2461:31)
    at TypeScriptParserMixin.parseExport (/Users/oliverash/Development/temp/prettier-test/node_modules/@babel/parser/src/parser/statement.ts:2364:29)
    at TypeScriptParserMixin.parseExport (/Users/oliverash/Development/temp/prettier-test/node_modules/@babel/parser/src/plugins/typescript/index.ts:2767:22)
    at TypeScriptParserMixin.parseStatementContent (/Users/oliverash/Development/temp/prettier-test/node_modules/@babel/parser/src/parser/statement.ts:580:25)
    at TypeScriptParserMixin.parseStatementContent (/Users/oliverash/Development/temp/prettier-test/node_modules/@babel/parser/src/plugins/typescript/index.ts:2857:20)
    at TypeScriptParserMixin.parseStatementLike (/Users/oliverash/Development/temp/prettier-test/node_modules/@babel/parser/src/parser/statement.ts:416:17)
    at TypeScriptParserMixin.parseModuleItem (/Users/oliverash/Development/temp/prettier-test/node_modules/@babel/parser/src/parser/statement.ts:353:17)
    at TypeScriptParserMixin.parseBlockOrModuleBlockBody (/Users/oliverash/Development/temp/prettier-test/node_modules/@babel/parser/src/parser/statement.ts:1362:16)
    at TypeScriptParserMixin.parseBlockBody (/Users/oliverash/Development/temp/prettier-test/node_modules/@babel/parser/src/parser/statement.ts:1336:10)
    at TypeScriptParserMixin.parseProgram (/Users/oliverash/Development/temp/prettier-test/node_modules/@babel/parser/src/parser/statement.ts:226:10)
    at TypeScriptParserMixin.parseTopLevel (/Users/oliverash/Development/temp/prettier-test/node_modules/@babel/parser/src/parser/statement.ts:208:25)
    at TypeScriptParserMixin.parse (/Users/oliverash/Development/temp/prettier-test/node_modules/@babel/parser/src/parser/index.ts:45:10)
    at TypeScriptParserMixin.parse (/Users/oliverash/Development/temp/prettier-test/node_modules/@babel/parser/src/plugins/typescript/index.ts:3974:20)
    at parse (/Users/oliverash/Development/temp/prettier-test/node_modules/@babel/parser/src/index.ts:67:38)
    at preprocessor (/Users/oliverash/Development/temp/prettier-test/node_modules/@trivago/prettier-plugin-sort-imports/lib/src/preprocessors/preprocessor.js:15:34)
    at Object.defaultPreprocessor [as preprocess] (/Users/oliverash/Development/temp/prettier-test/node_modules/@trivago/prettier-plugin-sort-imports/lib/src/preprocessors/default-processor.js:9:44)
    at Object.parse (/Users/oliverash/Development/temp/prettier-test/node_modules/prettier/index.js:7511:25)
    at coreFormat (/Users/oliverash/Development/temp/prettier-test/node_modules/prettier/index.js:8829:18)
    at formatWithCursor2 (/Users/oliverash/Development/temp/prettier-test/node_modules/prettier/index.js:9021:18)
    at /Users/oliverash/Development/temp/prettier-test/node_modules/prettier/index.js:38176:12
    at Object.format (/Users/oliverash/Development/temp/prettier-test/node_modules/prettier/index.js:38190:12)
    at t.default.format (/Users/oliverash/.vscode/extensions/esbenp.prettier-vscode-9.10.4/dist/extension.js:1:14731)
    at t.PrettierEditProvider.provideEdits (/Users/oliverash/.vscode/extensions/esbenp.prettier-vscode-9.10.4/dist/extension.js:1:11417)
    at q.provideDocumentFormattingEdits (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:39883)
["INFO" - 08:38:26] Formatting completed in 93ms.
```

**Comment by OliverJAsh** [comment]
It looks like we need pass `dts: true` to Babel's TypeScript plugin ([reference](https://github.com/babel/babel/issues/14871#issuecomment-1223880338)) e.g.:

```ts
babel.parseSync(source, {
  plugins: [
    ["typescript", { dts: true }]
  ]
});
```
