### ISSUE TITLE
Plugin crashes reading file: Cannot read properties of undefined (reading 'buildError')

### ISSUE THREAD

**Issue by jspradlin1-chwy** [trivago/prettier-plugin-sort-imports#287]
**Your Environment**
 * **Prettier version**: 3.1.0
 * **node version** 20.11.1
 * **package manager**: npm@10.2.4
 * **IDE**: [CLI, IntelliJ]

**Describe the bug**

plugin throws an error when parsing a specific file.

**To Reproduce**

parse this file:
```ts
import { Factory } from 'rosie';

import { InsurancePlanCode } from '@src/helpers/plan-constants.helper';
import {
  CoInsurancePercentage,
  DeductibleDollars,
} from '@src/helpers/quote-product.helper';
import {
  Financials,
  QuoteSelectionPet,
  SelectedQuoteProduct,
} from '@src/@types/quotes';
import freeze from '@test/helpers/freeze';
import SelectedQuoteProductsFactory, {
  SelectableProductCodes,
} from '@test/fixtures/selected-quote-products';

const QuoteSelectionPet = new Factory<QuoteSelectionPet>()

class QuoteSelectionPetsFactory {
  build(
    name: 'QuoteSelectionPet',
  ): QuoteSelectionPet {
    return freeze(QuoteSelectionPet.build(attrs, options));
  }
}

export default new QuoteSelectionPetsFactory();
```

**Expected behavior**

Prettier (with the help of the plugin) should be able to:
1 - Detect when the imports aren't sorted properly (without --write)
or 
2 - sort the imports properly (with --write)

**Screenshots, code sample, etc**
<img width="1432" alt="image" src="https://github.com/trivago/prettier-plugin-sort-imports/assets/87656333/f2f5342f-028b-40bb-a60c-4fb1211c1aa6">

**Configuration File (cat .prettierrc, prettier.config.js, .prettier.js)**
```json
  "prettier": {
    "semi": true,
    "trailingComma": "all",
    "singleQuote": true,
    "importOrder": [
      "^@src/(.*)(?<!css)$",
      "^@test/(.*)$",
      "^[./]",
      "^(.*)\\.s?css$"
    ],
    "importOrderSeparation": true,
    "importOrderSortSpecifiers": true,
    "plugins": [
      "prettier-plugin-java",
      "@trivago/prettier-plugin-sort-imports"
    ]
  },```
<!-- Please be careful do not leak any sensitive information, remove tokens -->

**Error log**
```
~/IdeaProjects/hc-pet-insurance  % npx prettier --write src/test/js/fixtures/quote-selection-pets.ts
src/test/js/fixtures/quote-selection-pets.ts
[error] src/test/js/fixtures/quote-selection-pets.ts: TypeError: Cannot read properties of undefined (reading 'buildError')
[error]     at Scope.checkBlockScopedCollisions (/Users/jspradlin1/IdeaProjects/hc-pet-insurance/node_modules/@trivago/prettier-plugin-sort-imports/node_modules/@babel/traverse/lib/scope/index.js:399:22)
[error]     at Scope.registerBinding (/Users/jspradlin1/IdeaProjects/hc-pet-insurance/node_modules/@trivago/prettier-plugin-sort-imports/node_modules/@babel/traverse/lib/scope/index.js:535:16)
[error]     at Scope.registerDeclaration (/Users/jspradlin1/IdeaProjects/hc-pet-insurance/node_modules/@trivago/prettier-plugin-sort-imports/node_modules/@babel/traverse/lib/scope/index.js:487:14)
[error]     at Object.BlockScoped (/Users/jspradlin1/IdeaProjects/hc-pet-insurance/node_modules/@trivago/prettier-plugin-sort-imports/node_modules/@babel/traverse/lib/scope/index.js:254:12)
[error]     at Object.newFn (/Users/jspradlin1/IdeaProjects/hc-pet-insurance/node_modules/@trivago/prettier-plugin-sort-imports/node_modules/@babel/traverse/lib/visitors.js:192:17)
[error]     at NodePath._call (/Users/jspradlin1/IdeaProjects/hc-pet-insurance/node_modules/@trivago/prettier-plugin-sort-imports/node_modules/@babel/traverse/lib/path/context.js:46:20)
[error]     at NodePath.call (/Users/jspradlin1/IdeaProjects/hc-pet-insurance/node_modules/@trivago/prettier-plugin-sort-imports/node_modules/@babel/traverse/lib/path/context.js:32:14)
[error]     at NodePath.visit (/Users/jspradlin1/IdeaProjects/hc-pet-insurance/node_modules/@trivago/prettier-plugin-sort-imports/node_modules/@babel/traverse/lib/path/context.js:82:31)
[error]     at TraversalContext.visitQueue (/Users/jspradlin1/IdeaProjects/hc-pet-insurance/node_modules/@trivago/prettier-plugin-sort-imports/node_modules/@babel/traverse/lib/context.js:86:16)
[error]     at TraversalContext.visitMultiple (/Users/jspradlin1/IdeaProjects/hc-pet-insurance/node_modules/@trivago/prettier-plugin-sort-imports/node_modules/@babel/traverse/lib/context.js:61:17)
```

**Contribute to @trivago/prettier-plugin-sort-imports**

- [ ] I'm willing to fix this bug 🥇 

<!--

IMPORTANT: please do not attach external files, all content should be visible from any device.
-->

**Comment by AaronTrazona** [comment]
I encounter this issue too.

**Comment by mikitabut** [comment]
Same

**Comment by MohammadKurjieh** [comment]
I get this error when I have a variable and an imported type with the same type. Renaming one of them resolves the issue temporarily.

Example:

```TS
import type { User } from './userModal';
// ...
type UserModalType = Omit<User, 'id'>;
// ...
const User: UserModalType = {
 // ...
}
```

Temporary Fix:

```TS
import type { User as UserModal } from './userModal';
// ...
type UserModalType = Omit<UserModal, 'id'>;
// ...
const User: UserModalType = {
 // ...
}
```

**Comment by kuttyhub** [comment]
getting the same, error is there a solution for this?

**Comment by mbwestphal** [comment]
Getting the same error.

**Comment by igorakkerman** [comment]
Similar for me:
```
[error] Cannot read properties of undefined (reading 'async')
```
Prettier 3.5.1
Node 23.7.0

**Comment by mbwestphal** [comment]
That issue is being discussed here https://github.com/prettier/prettier/issues/17139
