### ISSUE TITLE
Error: Cannot find module 'prettier/parser-babel'

### ISSUE THREAD

**Issue by ktrzos** [trivago/prettier-plugin-sort-imports#77]
After adding `@trivago/prettier-plugin-sort-imports` to the project, I'm receiving an error when formatting:

Command:

```
/project_path/node_modules/.bin/prettier --write js/components/MyComponent.tsx
```

Error message:
```
Error: Cannot find module 'prettier/parser-babel'
Require stack:
- /project_path/node_modules/@trivago/prettier-plugin-sort-imports/lib/src/index.js
- /project_path/node_modules/prettier/bin-prettier.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/project_path/node_modules/@trivago/prettier-plugin-sort-imports/lib/src/index.js:14:22)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/project_path/node_modules/@trivago/prettier-plugin-sort-imports/lib/src/index.js',
    '/project_path/node_modules/prettier/bin-prettier.js'
  ]

```

Here's my `.prettierrc`:

```
{
  "trailingComma": "all",
  "singleQuote": true,
  "printWidth": 100,
  "importOrder": [
    "(.*).scss$",
    "(^react$)|(^react-(.*)$)",
    "(^[a-z_-]+$)|(^@(.*)/(.*)$)",
    "^components/(.*)$",
    "^[./]"
  ],
  "importOrderSeparation": true
}
```

Any ideas what could be wrong 🙁?

**Comment by ktrzos** [comment]
Can anyone help with this issue, please? 🙂

**Comment by ktrzos** [comment]
I just realized, that I was using old version of Prettier (`^1.18.2`). Upgraded to `^2.4.1` and it works fine 👍️.
